import type { StoryNode } from "./types";

export const NODES: Record<string, StoryNode> = {
  intro_1: {
    loc: "Порог",
    bg: "threshold",
    text: "Ты открываешь глаза.\n\nНе болит. Не холодно. Не жарко. Просто — есть.\n\nВокруг — зал с высокими арками. Свет не белый и не золотой: он прошёл сквозь тёмное стекло. Под ногами камень, гладкий от множества шагов.",
    next: "intro_2",
  },
  intro_2: {
    loc: "Порог",
    bg: "threshold",
    text: "Где-то вдалеке — не крики и не плач. Голоса. Шаги. Жизнь.\n\nТы не помнишь, как сюда попал. Помнишь только, что что-то закончилось.",
    next: "intro_3",
  },
  intro_3: {
    loc: "Порог",
    bg: "threshold",
    speaker: "???",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Не нужно искать дверь назад. Её нет.\n\nГолос спокойный, низкий, чуть насмешливый. Из тени у колонны выходит фигура.",
    next: "intro_4",
  },
  intro_4: {
    loc: "Порог",
    bg: "threshold",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "Высокий. Тёмные волосы. Одежда — между строгим платьем и военной формой, золотая вышивка едва заметна.\n\nГлаза смотрят прямо. Не злобно. Оценивающе.",
    next: "intro_5",
  },
  intro_5: {
    loc: "Порог",
    bg: "threshold",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Добро пожаловать в Верхний Ад. Я — Люцифер. Здесь я отвечаю за порядок. Не за пытки. За порядок.\n\nОн даёт тебе время осознать слова.",
    choices: [
      { text: "— Это… действительно Ад?", next: "intro_q1" },
      { text: "— Почему я здесь?", next: "intro_q2" },
      { text: "Молчать и смотреть.", next: "intro_q3", trust: { lucifer: 1 } },
    ],
  },
  intro_q1: {
    loc: "Порог",
    bg: "threshold",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Да. Только не тот, о котором рассказывали в церквях и на картинах.\n\nЗдесь есть улицы, дома, библиотеки. Люди, которые работают, спорят, дружат и иногда смеются. Небесная канцелярия по-прежнему ставит печати. Но жить — можно.",
    next: "intro_rules",
  },
  intro_q2: {
    loc: "Порог",
    bg: "threshold",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Потому что твоё дело оказалось недостаточно «чистым» для Неба и недостаточно «чудовищным» для Нижнего Ада. Ты попал в пространство между.\n\nВерхний Ад — не наказание. Это место, где ещё можно быть кем-то, кроме записи в журнале.",
    next: "intro_rules",
  },
  intro_q3: {
    loc: "Порог",
    bg: "threshold",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Умно. Сначала слушать.\n\nОн почти улыбается уголком рта.\n\n— Здесь не требуют немедленных ответов. Но любопытство приветствуется. Ты не в котле. Здесь живут.",
    next: "intro_rules",
  },
  intro_rules: {
    loc: "Порог",
    bg: "threshold",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Правила просты. Не пытайся «искупить» себя страданием — это здесь не работает. Не лги себе о том, кем ты был. И не позволяй чужим категориям становиться твоим единственным именем.\n\nОн поворачивается.\n\n— Пойдём. Покажу тебе город.",
    flag: "met_lucifer",
    journal: "upper_hell",
    unlockChar: { id: "lucifer", level: 1 },
    next: "street_1",
  },

  street_1: {
    loc: "Улицы Верхнего Ада",
    bg: "street",
    journal: "living_city",
    text: "Зал Порога сменяется узкой улицей. Тёмный камень, окна с тёплым светом. Где-то играет музыка — странная, но не тревожная. Души идут по делам: книги, спор у лавки, кто-то сидит на ступеньках.",
    next: "street_2",
  },
  street_2: {
    loc: "Улицы Верхнего Ада",
    bg: "street",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Видишь? Не рай. Но и не клетка. Мы построили это сами — те, кого Небо решило не принимать и не уничтожать окончательно.",
    next: "street_3",
  },
  street_3: {
    loc: "Улицы Верхнего Ада",
    bg: "street",
    chars: ["elias"],
    text: "У стены старого здания стоит молодой человек. На вид — лет двадцать. Тёмные волосы, свободная закрытая одежда приглушённых тонов. Смотрит в сторону, будто боится, что на него обратят внимание.\n\nКогда взгляды пересекаются, он быстро отводит глаза.",
    next: "street_4",
  },
  street_4: {
    loc: "Улицы Верхнего Ада",
    bg: "street",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer", "elias"],
    text: "— Это Элиас. Недавно прибыл. Пока ещё учится, что здесь можно просто… быть.\n\nВ голосе нет насмешки. Скорее — сдержанное внимание.",
    choices: [
      { text: "Подойти и поздороваться.", next: "elias_meet_1", trust: { elias: 1 } },
      { text: "Спросить Люцифера о нём.", next: "elias_ask_lucifer" },
      { text: "Пройти мимо. Пока рано.", next: "street_pass" },
    ],
  },
  elias_meet_1: {
    loc: "Улицы Верхнего Ада",
    bg: "street",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "Ты подходишь. Он вздрагивает — едва заметно — и выпрямляется, будто готовясь к чему-то неприятному.\n\n— …Здравствуй. Ты тоже новый?",
    unlockChar: { id: "elias", level: 1 },
    next: "elias_meet_2",
  },
  elias_meet_2: {
    loc: "Улицы Верхнего Ада",
    bg: "street",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "Голос тихий. Он смотрит то на тебя, то мимо — привычка проверять, не раздражает ли он собеседника.",
    choices: [
      { text: "— Да. Только что. Меня зовут {name}.", next: "elias_meet_name", trust: { elias: 1 } },
      { text: "— Не бойся. Я не собираюсь ничего требовать.", next: "elias_meet_safe", trust: { elias: 2 } },
      { text: "— Люцифер сказал, что ты недавно здесь.", next: "elias_meet_luc" },
    ],
  },
  elias_meet_name: {
    loc: "Улицы Верхнего Ада",
    bg: "street",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "— Элиас. Элиас Морроу.\n\nОн произносит имя так, будто всё ещё не уверен, можно ли им пользоваться. Потом тише:\n\n— Рад… то есть. Хорошо, что встретили.",
    next: "elias_meet_end",
  },
  elias_meet_safe: {
    loc: "Улицы Верхнего Ада",
    bg: "street",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "Он смотрит чуть дольше обычного. Удивление и осторожная благодарность.\n\n— …Спасибо. Я Элиас. Просто Элиас.\n\nПлечи чуть опускаются — будто на секунду стало легче.",
    next: "elias_meet_end",
  },
  elias_meet_luc: {
    loc: "Улицы Верхнего Ада",
    bg: "street",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "— Да. Он… не такой, как я думал. Не кричит. Не приказывает страдать.\n\nЭлиас переводит взгляд на Люцифера, потом на тебя.\n\n— Я Элиас Морроу. Если… если можно.",
    next: "elias_meet_end",
  },
  elias_meet_end: {
    loc: "Улицы Верхнего Ада",
    bg: "street",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer", "elias"],
    text: "— Хорошо. Знакомство состоялось. Элиас, если захочешь — присоединись позже. Сейчас нам в библиотеку. Дион уже заждался.",
    next: "to_library",
  },
  elias_ask_lucifer: {
    loc: "Улицы Верхнего Ада",
    bg: "street",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Его дело… сложное. Канцелярия поставила две печати. Одна — редчайшее исключение. Другая — типичная для тех, кого система видит только через одну призму.\n\nДеталей он не раскрывает.\n\n— Подойди сам, если хочешь. Здесь никого не заставляют дружить.",
    unlockChar: { id: "elias", level: 1 },
    choices: [
      { text: "Всё же подойти.", next: "elias_meet_1", trust: { elias: 1 } },
      { text: "Пока оставить.", next: "street_pass" },
    ],
  },
  street_pass: {
    loc: "Улицы Верхнего Ада",
    bg: "street",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Как пожелаешь. У вас ещё будет время.\n\nВы проходите мимо. Элиас не поднимает головы.",
    unlockChar: { id: "elias", level: 1 },
    next: "to_library",
  },

  to_library: {
    loc: "Библиотека",
    bg: "library",
    text: "Библиотека не похожа на склеп. Высокие стеллажи, тёплый свет ламп, запах бумаги и старого дерева. В углу — низкий столик с шахматной доской.",
    next: "dion_1",
  },
  dion_1: {
    loc: "Библиотека",
    bg: "library",
    chars: ["dion"],
    text: "За столиком сидит мальчик. На вид — лет тринадцать. Тёмные волосы, чуть заострённые уши, тонкий хвост. Рядом — книга на языке, который ты не сразу узнаёшь, и маленький складной нож.",
    next: "dion_2",
  },
  dion_2: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Дион",
    speakerId: "dion",
    chars: ["dion"],
    text: "— О. Новый.\n\nВзгляд умный, прямой, без детской робости.\n\n— Отец сказал, что приведёт кого-то. Я Дион. Можешь не кланяться. Я не люблю, когда кланяются.",
    unlockChar: { id: "dion", level: 1 },
    flag: "met_dion",
    next: "dion_3",
  },
  dion_3: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer", "dion"],
    text: "— Дион — мой сын. И сын Лилит. Не дай себя обмануть возрастом лица. Он читал больше философов, чем большинство живых профессоров, и иногда играет в шахматы… с весьма высокопоставленным партнёром.",
    next: "dion_4",
  },
  dion_4: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Дион",
    speakerId: "dion",
    chars: ["dion"],
    text: "— С Богом. Да. Он ходит конями странно, но партии бывают интересные.\n\nДион склоняет голову, разглядывая тебя.\n\n— А ты — человек. Настоящий. Я никогда не был обычным человеческим ребёнком. Расскажи что-нибудь. Как пахнет дождь. Как больно, когда падаешь. Что чувствуешь, когда тебя обнимают без причины.",
    choices: [
      { text: "Рассказать что-то простое и человеческое.", next: "dion_human", trust: { dion: 2 } },
      { text: "— Почему тебе это важно?", next: "dion_why", trust: { dion: 1 } },
      { text: "— Я сам ещё мало что помню.", next: "dion_memory" },
    ],
  },
  dion_human: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Дион",
    speakerId: "dion",
    chars: ["dion"],
    text: "Ты говоришь — о мокром асфальте, о ссадинах на коленях, о тепле чужого плеча.\n\nДион не перебивает. Потом кивает.\n\n— Спасибо. Это полезно. Отец редко говорит о таких вещах. Он слишком занят тем, чтобы Ад не стал клеткой.",
    next: "dion_end",
  },
  dion_why: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Дион",
    speakerId: "dion",
    chars: ["dion"],
    text: "— Потому что я никогда этого не знал. Я родился здесь. Я знаю греческий, латынь, мёртвые диалекты и дебюты, которых нет в человеческих учебниках.\n\nНо не знаю, каково быть маленьким и не понимать, почему взрослые грустят.\n\n— Любопытство. И немного зависти.",
    next: "dion_end",
  },
  dion_memory: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Дион",
    speakerId: "dion",
    chars: ["dion"],
    text: "— Тогда мы в чём-то похожи. Я помню слишком много чужого и слишком мало своего.\n\nУлыбка почти взрослая.\n\n— Когда вспомнишь — приходи. Я буду здесь. Или в саду. Или буду мешать отцу на совещаниях.",
    next: "dion_end",
  },
  dion_end: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer", "dion"],
    text: "— Хватит допрашивать новоприбывшего.\n\nДион закатывает глаза.\n\n— Как скажешь. Только не делай из него очередное «дело».",
    next: "after_library",
  },
  after_library: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Завтра визит. Небесная канцелярия вызвала одно дело на сверку. Элиас должен присутствовать. Я тоже. Ты можешь пойти — если хочешь увидеть, как система решает, кем ты являешься на бумаге.",
    choices: [
      { text: "— Я пойду.", next: "decide_office_yes", trust: { lucifer: 1 }, flag: "go_office" },
      { text: "— Мне нужно подумать.", next: "decide_office_think" },
      { text: "— Зачем мне это?", next: "decide_office_why" },
    ],
  },
  decide_office_yes: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Хорошо. Готовься. Там холодно. Не температурой — отношением.",
    next: "evening_1",
  },
  decide_office_think: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Думай. Но не слишком долго. Некоторые вещи лучше увидеть, чем услышать в пересказе.",
    next: "evening_1",
  },
  decide_office_why: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Чтобы понять разницу между человеком и записью о нём. Если неинтересно — оставайся. Никто не заставляет.",
    choices: [
      { text: "— Тогда я пойду.", next: "decide_office_yes", flag: "go_office", trust: { lucifer: 1 } },
      { text: "— Пока останусь здесь.", next: "evening_1", flag: "skip_office" },
    ],
  },

  evening_1: {
    loc: "Улицы / Вечер",
    bg: "street",
    text: "Вечер не приносит человеческой темноты. Свет становится глубже, окна ярче. Где-то играет тихая музыка. В витрине странного магазина продают стёкла, в которых отражается не лицо, а настроение.",
    next: "evening_2",
  },
  evening_2: {
    loc: "Улицы / Вечер",
    bg: "street",
    chars: ["elias"],
    text: "Элиас снова здесь. Сидит на низкой ограде у сада, руки в рукавах свободной куртки. Выглядит так, будто пытается стать меньше.",
    choices: [
      { text: "Подойти и сесть рядом.", next: "elias_eve_1", reqTrust: { elias: 1 } },
      { text: "Подойти, держась на расстоянии.", next: "elias_eve_soft" },
      { text: "Оставить его в покое.", next: "evening_alone" },
    ],
  },
  elias_eve_1: {
    loc: "Сад",
    bg: "garden",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "Он не вздрагивает. Только смотрит искоса.\n\n— Привет.\n\nПауза.\n\n— Здесь спокойнее, чем я думал. Я всё ждал, что начнётся. Наказание. Огонь. А вместо этого — улицы и библиотека.",
    next: "elias_eve_2",
  },
  elias_eve_soft: {
    loc: "Сад",
    bg: "garden",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "— …Привет.\n\nКивок. Не уверен, можно ли продолжать.\n\n— Ты не обязан со мной говорить. Правда.",
    choices: [
      { text: "— Хочу. Если ты не против.", next: "elias_eve_1", trust: { elias: 1 } },
      { text: "— Тогда просто посижу рядом.", next: "elias_eve_quiet", trust: { elias: 1 } },
    ],
  },
  elias_eve_quiet: {
    loc: "Сад",
    bg: "garden",
    chars: ["elias"],
    text: "Вы сидите молча. Элиас постепенно расслабляется. Иногда бросает взгляд — проверяет, не раздражает ли присутствие. Не раздражает.",
    next: "elias_eve_2",
  },
  elias_eve_2: {
    loc: "Сад",
    bg: "garden",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "— Меня в жизни звали иначе. Не Элиас. Сценическое имя. Blue Velvet.\n\nПочти шёпот, будто признаётся в стыдном.\n\n— Я думал, что после смерти меня будут звать только так. Или по номеру дела.",
    unlockChar: { id: "elias", level: 2 },
    journal: "lust_prisoner",
    choices: [
      { text: "— Как ты хочешь, чтобы тебя называли?", next: "elias_name_choice", trust: { elias: 2 } },
      { text: "— Дело — не ты.", next: "elias_not_case", trust: { elias: 2 } },
      { text: "Просто слушать.", next: "elias_listen", trust: { elias: 1 } },
    ],
  },
  elias_name_choice: {
    loc: "Сад",
    bg: "garden",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "— Элиас. Пожалуйста. Просто Элиас.\n\nРобкая улыбка, будто не привык, что она может быть безопасной.\n\n— Спасибо, что спросил.",
    next: "elias_eve_3",
  },
  elias_not_case: {
    loc: "Сад",
    bg: "garden",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "Он смотрит долго.\n\n— Люцифер говорит что-то похожее. Я пока не умею в это верить. Но спасибо, что сказал.",
    journal: "person_not_case",
    next: "elias_eve_3",
  },
  elias_listen: {
    loc: "Сад",
    bg: "garden",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "Он продолжает осторожно: что после смерти ждал худшего. Что свободная одежда здесь — маленькое облегчение. Что не знает, имеет ли право на покой.",
    next: "elias_eve_3",
  },
  elias_eve_3: {
    loc: "Сад",
    bg: "garden",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "— Завтра меня вызывают. В канцелярию. Люцифер сказал, что пойдёт со мной.\n\nСжимает пальцы.\n\n— Я боюсь, что там снова будут говорить только категориями.",
    next: "evening_end",
  },
  evening_alone: {
    loc: "Улицы / Вечер",
    bg: "street",
    text: "Ты оставляешь Элиаса. В Верхнем Аду достаточно мест, где можно просто идти. Но на краю сознания остаётся его силуэт у ограды.",
    next: "evening_end",
  },
  evening_end: {
    loc: "Верхний Ад",
    bg: "night",
    text: "Ночь проходит странно — без сновидений и без бессонницы. Ты просто есть. Утром Люцифер находит тебя сам.",
    next: "office_decide",
  },

  office_decide: {
    loc: "Порог / Утро",
    bg: "threshold",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "— Пора. Элиас уже ждёт. Ты идёшь с нами в Небесную канцелярию?",
    choices: [
      { text: "— Да.", next: "office_1", flag: "go_office", reqFlagNot: "skip_office" },
      { text: "— Нет. Останусь.", next: "no_office_1", flag: "skip_office" },
    ],
  },

  office_1: {
    loc: "Путь к Канцелярии",
    bg: "heaven",
    journal: "heavenly_office",
    text: "Переход — как резкая смена воздуха. Свет белеет, холодеет. Пространство идеально ровное. Коридоры, двери с номерами дел, тишина, в которой слышно дыхание.",
    next: "office_2",
  },
  office_2: {
    loc: "Небесная канцелярия",
    bg: "heaven",
    chars: ["lucifer", "elias"],
    text: "Элиас идёт чуть позади. Плечи напряжены. Люцифер — впереди, будто это его территория тоже, хотя формально здесь правят другие.",
    next: "office_3",
  },
  office_3: {
    loc: "Небесная канцелярия",
    bg: "heaven",
    speaker: "Ангел-делопроизводитель",
    speakerId: "angel",
    chars: ["angel", "elias", "lucifer"],
    text: "— Дело. Каинова кровь. Пленник похоти. Предстать для сверки классификации.\n\nГолос ровный, без злобы и без тепла. Инвентарная опись.",
    unlockChar: { id: "elias", level: 2 },
    journal: ["cain_blood", "lust_prisoner"],
    next: "office_4",
  },
  office_4: {
    loc: "Небесная канцелярия",
    bg: "heaven",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias", "angel"],
    text: "Элиас стоит прямо, пальцы дрожат.\n\n— Я… Элиас Морроу.",
    next: "office_5",
  },
  office_5: {
    loc: "Небесная канцелярия",
    bg: "heaven",
    speaker: "Ангел-делопроизводитель",
    speakerId: "angel",
    chars: ["angel"],
    text: "— В протоколе вы проходите как носитель указанных категорий. Имя при жизни вторично. Сверка касается соответствия печатей текущему состоянию души.",
    next: "office_6",
  },
  office_6: {
    loc: "Небесная канцелярия",
    bg: "heaven",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer", "angel", "elias"],
    text: "— Нет.\n\nСлово короткое. Сталь.\n\n— Перед вами не «носитель категорий». Перед вами человек. Элиас Морроу. Первая печать — редчайшее исключение: он защищал собственную жизнь. Вторая — результат системы, которая видит только поверхность. Вы будете обращаться к нему по имени.",
    unlockChar: { id: "lucifer", level: 2 },
    journal: "person_not_case",
    next: "office_7",
  },
  office_7: {
    loc: "Небесная канцелярия",
    bg: "heaven",
    speaker: "Ангел-делопроизводитель",
    speakerId: "angel",
    chars: ["angel", "lucifer"],
    text: "Пауза. Ангел смотрит без страха — с усталой привычкой к таким возражениям.\n\n— Правила предусматривают классификационные маркеры. Однако… зафиксирую требование. Элиас Морроу. Сверка продолжается.",
    next: "office_8",
  },
  office_8: {
    loc: "Небесная канцелярия",
    bg: "heaven",
    chars: ["elias", "lucifer", "angel"],
    text: "Элиас смотрит на Люцифера — благодарность и страх, что защита временна.\n\nАнгел ждёт. Ты тоже часть этой комнаты.",
    choices: [
      { text: "Поддержать Люцифера вслух.", next: "office_support_l", trust: { lucifer: 2, elias: 1 } },
      { text: "Тихо сказать Элиасу, что он не сводится к делу.", next: "office_support_e", trust: { elias: 2 } },
      { text: "Молча наблюдать.", next: "office_watch" },
      {
        text: "— Категории существуют не зря. Иначе не будет порядка.",
        next: "office_case",
        flag: "case_view",
        trust: { lucifer: -1, elias: -1 },
      },
    ],
  },
  office_support_l: {
    loc: "Небесная канцелярия",
    bg: "heaven",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "Короткий взгляд — одобряющий, сдержанный.\n\n— Видишь? Даже новоприбывшие понимают разницу.",
    next: "office_9",
  },
  office_support_e: {
    loc: "Небесная канцелярия",
    bg: "heaven",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "Едва заметный кивок. Глаза блестят от напряжения, которое чуть отпустило.\n\nШёпот:\n\n— Спасибо.",
    next: "office_9",
  },
  office_watch: {
    loc: "Небесная канцелярия",
    bg: "heaven",
    chars: ["lucifer", "elias", "angel"],
    text: "Ты молчишь. Люцифер не сдаёт позиций. Ангел заполняет формы. Элиас дышит ровнее.",
    next: "office_9",
  },
  office_case: {
    loc: "Небесная канцелярия",
    bg: "heaven",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "Люцифер смотрит на тебя так, будто пересчитал.\n\n— Порядок, который не умеет сомневаться, — это леность. Запомни это. Даже если тебе сейчас удобнее бумага.",
    next: "office_9",
  },
  office_9: {
    loc: "Небесная канцелярия",
    bg: "heaven",
    speaker: "Ангел-делопроизводитель",
    speakerId: "angel",
    chars: ["angel"],
    text: "— По категории «Каинова кровь»: отмечено обстоятельство самообороны. Вопрос о снятии печати — на рассмотрение выше. По второй категории изменения не вносятся на данном этапе.\n\nМожете быть свободны.",
    unlockChar: { id: "elias", level: 3 },
    next: "office_10",
  },
  office_10: {
    loc: "Путь обратно",
    bg: "threshold",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer", "elias"],
    text: "По дороге назад Люцифер говорит тихо, больше себе:\n\n— Они называют это порядком. Я называю это ленью ума. Проще поставить печать, чем увидеть человека.",
    next: "corridor_choice",
  },
  corridor_choice: {
    loc: "Старый коридор",
    bg: "threshold",
    text: "На обратном пути открывается боковой проход. Воздух там старше. Люцифер останавливается.\n\n— Это не для всех. Там живёт тот, чьё имя канцелярия использует как штамп. Каин. Он не принимает посетителей. Иногда — терпит свидетелей.",
    unlockChar: { id: "cain", level: 1 },
    choices: [
      { text: "Попросить провести.", next: "cain_1", trust: { cain: 1 }, flag: "met_cain" },
      { text: "Не тревожить древнее.", next: "after_office" },
    ],
  },

  cain_1: {
    loc: "Порог Каина",
    bg: "office",
    speaker: "Каин",
    speakerId: "cain",
    chars: ["cain"],
    text: "Он сидит так, будто сидел всегда. Лицо выветрилось временем, не злобой. На лбу — след, который не хочет быть символом и всё равно им стал.\n\n— Ещё один, кто пришёл посмотреть на оригинал штампа.",
    unlockChar: { id: "cain", level: 2 },
    next: "cain_2",
  },
  cain_2: {
    loc: "Порог Каина",
    bg: "office",
    speaker: "Каин",
    speakerId: "cain",
    chars: ["cain"],
    text: "— Мальчика из канцелярии я знаю. Не лично. По эху. Его назвали моей кровью, хотя его история — не моя.\n\nГолос ровный.\n\n— Меня тоже когда-то свели к одному дню. С тех пор я учусь быть больше, чем этот день. Получается плохо. Но я не сдаюсь дню.",
    choices: [
      { text: "— Он не ты.", next: "cain_not", trust: { cain: 2, elias: 1 } },
      { text: "— Что ты хочешь, чтобы о тебе помнили?", next: "cain_remember", trust: { cain: 2 } },
      { text: "Молчать. Присутствие — уже много.", next: "cain_silent", trust: { cain: 1 } },
    ],
  },
  cain_not: {
    loc: "Порог Каина",
    bg: "office",
    speaker: "Каин",
    speakerId: "cain",
    chars: ["cain"],
    text: "— Именно. Скажи это канцелярии тысячу раз. Они всё равно экономят чернила.\n\nПочти улыбка — страшная своей усталостью.\n\n— Иди. Не становись чьим-то эхом.",
    next: "after_office",
  },
  cain_remember: {
    loc: "Порог Каина",
    bg: "office",
    speaker: "Каин",
    speakerId: "cain",
    chars: ["cain"],
    text: "— Брата. Не удар. Брата.\n\nОн закрывает глаза.\n\n— Если система умеет помнить только преступление, она ничего не помнит.",
    next: "after_office",
  },
  cain_silent: {
    loc: "Порог Каина",
    bg: "office",
    speaker: "Каин",
    speakerId: "cain",
    chars: ["cain"],
    text: "Он кивает — почти благодарно.\n\n— Редко кто выдерживает тишину без желания меня исправить. Можешь идти.",
    next: "after_office",
  },

  no_office_1: {
    loc: "Верхний Ад",
    bg: "street",
    text: "Ты остаёшься. Улицы живут. Где-то Дион снова читает. Где-то Элиас проходит через то, чего ты решил не видеть.",
    next: "no_office_2",
  },
  no_office_2: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Дион",
    speakerId: "dion",
    chars: ["dion"],
    text: "— Не пошёл?\n\nНе разочарование — интерес.\n\n— Отец сказал, что канцелярия сегодня будет особенно канцелярской. Иногда полезно не смотреть. Иногда — обязательно смотреть. Ты выбрал.",
    trust: { dion: 1 },
    next: "no_office_3",
  },
  no_office_3: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Дион",
    speakerId: "dion",
    chars: ["dion"],
    text: "— Хочешь партию? Я поддамся. Немного.",
    choices: [
      { text: "Сыграть.", next: "dion_chess", trust: { dion: 2 } },
      { text: "— Лучше поговорить.", next: "dion_talk", trust: { dion: 1 } },
      { text: "Отказаться и ждать Элиаса.", next: "wait_elias" },
    ],
  },
  dion_chess: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Дион",
    speakerId: "dion",
    chars: ["dion"],
    text: "Партия короткая. Дион чуть поддаётся — и всё равно выигрывает.\n\n— Ты думаешь не как те, кто привык к правилам Неба. Это хорошо. Значит, ещё не всё потеряно.",
    unlockChar: { id: "dion", level: 2 },
    next: "after_office",
  },
  dion_talk: {
    loc: "Библиотека",
    bg: "library",
    speaker: "Дион",
    speakerId: "dion",
    chars: ["dion"],
    text: "Вы говорите о книгах, о страхе тишины, о том, что такое дом. Дион слушает жадно.\n\n— Когда-нибудь я пойму. А пока — собираю осколки.",
    unlockChar: { id: "dion", level: 2 },
    next: "after_office",
  },
  wait_elias: {
    loc: "Улицы",
    bg: "street",
    chars: ["elias", "lucifer"],
    text: "Когда Элиас возвращается, он вымотан, но жив. Люцифер идёт рядом — молчаливый и мрачный.",
    next: "after_office",
  },

  after_office: {
    loc: "Верхний Ад",
    bg: "street",
    text: "День клонится. Мир Ада чуть больше открылся — или чуть больше показал трещины.",
    next: "elias_deep_gate",
  },
  elias_deep_gate: {
    loc: "Сад",
    bg: "garden",
    text: "Позже Элиас стоит у тех же цветов. Если между вами уже есть нить — он может сказать больше. Если нет — останется силуэтом.",
    choices: [
      {
        text: "Сесть рядом. Молчать, пока он сам не заговорит.",
        next: "elias_deep_1",
        reqTrust: { elias: 3 },
      },
      { text: "Кивнуть издалека и идти дальше.", next: "lilith_1" },
    ],
  },
  elias_deep_1: {
    loc: "Сад",
    bg: "garden",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "Долго молчит. Потом:\n\n— Первая печать. Отец. Он… пытался меня убить. Я не хотел. Я просто не хотел умирать.\n\nГолос ровный от слишком долгой репетиции.\n\n— Канцелярия написала «Каинова кровь». Будто я продолжил чужую историю. А я просто остался жив.",
    unlockChar: { id: "elias", level: 3 },
    journal: "cain_blood",
    next: "elias_deep_2",
  },
  elias_deep_2: {
    loc: "Сад",
    bg: "garden",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "— Вторая печать проще для них. Я работал там, где тело становится товаром. Не потому что хотел делать зло. Потому что выхода, который был бы безопасным, не оказалось. Зависимость. Люди, которым было удобно, чтобы я не уходил.\n\nОн смотрит на свои руки в рукавах.\n\n— Здесь мне легче быть закрытым. Не на продажу.",
    unlockChar: { id: "elias", level: 4 },
    choices: [
      { text: "— Ты не обязан это отрабатывать.", next: "elias_deep_help", trust: { elias: 3 } },
      { text: "— Спасибо, что доверил.", next: "elias_deep_thanks", trust: { elias: 2 } },
      { text: "Не утешать. Просто остаться.", next: "elias_deep_stay", trust: { elias: 2 } },
    ],
  },
  elias_deep_help: {
    loc: "Сад",
    bg: "garden",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "Он смеётся коротко, почти беззвучно.\n\n— Я всю жизнь ждал счёт. А ты говоришь, что его нет.\n\nПауза.\n\n— Я попробую в это поверить. Медленно.",
    next: "lilith_1",
  },
  elias_deep_thanks: {
    loc: "Сад",
    bg: "garden",
    speaker: "Элиас",
    speakerId: "elias",
    chars: ["elias"],
    text: "— Я не умею принимать «спасибо» без поиска подвоха. Но сегодня… ладно. Приму.",
    next: "lilith_1",
  },
  elias_deep_stay: {
    loc: "Сад",
    bg: "garden",
    chars: ["elias"],
    text: "Вы сидите, пока свет в окнах становится гуще. Элиас больше не проверяет твоё настроение каждые десять секунд. Это уже близость.",
    next: "lilith_1",
  },

  lilith_1: {
    loc: "Сад Лилит",
    bg: "garden",
    chars: ["lilith", "dion"],
    text: "Во внутреннем саду — женщина. Высокая, тёмные волосы, взгляд, который не просит разрешения быть увиденным. Рядом Дион — явно не случайно.",
    next: "lilith_2",
  },
  lilith_2: {
    loc: "Сад Лилит",
    bg: "garden",
    speaker: "Лилит",
    speakerId: "lilith",
    chars: ["lilith"],
    text: "— Ты тот самый новый.\n\nНе вопрос.\n\n— Я Лилит. Не «жена Люцифера» и не «мать Диона» в первую очередь. Хотя и то, и другое — правда. У меня своё место в этом устроении.",
    unlockChar: { id: "lilith", level: 1 },
    next: "lilith_3",
  },
  lilith_3: {
    loc: "Сад Лилит",
    bg: "garden",
    speaker: "Лилит",
    speakerId: "lilith",
    chars: ["lilith", "dion"],
    text: "— Люцифер строит Ад как пространство, где ещё можно дышать. Я слежу, чтобы это пространство не стало новой клеткой — даже красивой. Дион пытается понять, каково быть человеком, не будучи им.\n\nА ты? Кем ты собираешься здесь стать?",
    choices: [
      { text: "— Тем, кто видит людей, а не дела.", next: "lilith_person", trust: { lilith: 2, lucifer: 1 } },
      { text: "— Пока не знаю. Смотрю.", next: "lilith_watch", trust: { lilith: 1 } },
      { text: "— Хочу понять систему и её пределы.", next: "lilith_system", trust: { lilith: 1 } },
    ],
  },
  lilith_person: {
    loc: "Сад Лилит",
    bg: "garden",
    speaker: "Лилит",
    speakerId: "lilith",
    chars: ["lilith"],
    text: "Кивает медленно.\n\n— Тогда тебе сюда. Но помнить: видеть человека — не значит оправдывать всё, что он сделал. Это значит не сводить его к одному слову в протоколе.",
    journal: "person_not_case",
    next: "lilith_4",
  },
  lilith_watch: {
    loc: "Сад Лилит",
    bg: "garden",
    speaker: "Лилит",
    speakerId: "lilith",
    chars: ["lilith"],
    text: "— Честный ответ. Смотри. Только не смотри слишком долго со стороны — однажды ты тоже станешь частью пейзажа.",
    next: "lilith_4",
  },
  lilith_system: {
    loc: "Сад Лилит",
    bg: "garden",
    speaker: "Лилит",
    speakerId: "lilith",
    chars: ["lilith"],
    text: "— Система нужна. Без неё — хаос. Но система, которая разучилась сомневаться, становится жестокой. Канцелярия разучилась.\n\nВзгляд острее.\n\n— Если пойдёшь этим путём — не потеряй человека за схемами.",
    next: "lilith_4",
  },
  lilith_4: {
    loc: "Сад Лилит",
    bg: "garden",
    speaker: "Лилит",
    speakerId: "lilith",
    chars: ["lilith"],
    text: "— Люцифер и я не «правим парой». Мы спорим. Иногда годами. Это тоже семья — не раствориться друг в друге.",
    unlockChar: { id: "lilith", level: 2 },
    choices: [
      { text: "Спросить Диона, каково расти между ними.", next: "dion_family", reqTrust: { dion: 2 }, trust: { dion: 1 } },
      { text: "Поблагодарить и уйти.", next: "lucifer_gate" },
    ],
  },
  dion_family: {
    loc: "Сад Лилит",
    bg: "garden",
    speaker: "Дион",
    speakerId: "dion",
    chars: ["dion", "lilith"],
    text: "— Шумно. Умно. Иногда одиноко, хотя оба дома.\n\nОн крутит нож, не открывая.\n\n— Они любят меня как идею и как сына сразу. Я учусь отделять одно от другого. Как люди.",
    unlockChar: { id: "dion", level: 3 },
    next: "lucifer_gate",
  },

  lucifer_gate: {
    loc: "Кабинет",
    bg: "office",
    text: "Дверь кабинета Люцифера приоткрыта. Можно пройти. Можно не тревожить правителя в его бумагах.",
    choices: [
      { text: "Войти.", next: "lucifer_private", reqTrust: { lucifer: 2 } },
      { text: "Оставить его.", next: "chapter_end_branch" },
    ],
  },
  lucifer_private: {
    loc: "Кабинет Люцифера",
    bg: "office",
    speaker: "Люцифер",
    speakerId: "lucifer",
    chars: ["lucifer"],
    text: "На столе — карты улиц, не круги наказания.\n\n— Садись. Я не буду тебя исповедовать.\n\nОн трёт переносицу.\n\n— Небо не зло. Оно устало. Усталость рождает штампы. Я строю Ад как возражение: здесь ещё можно передумать.",
    unlockChar: { id: "lucifer", level: 3 },
    trust: { lucifer: 1 },
    next: "chapter_end_branch",
  },

  chapter_end_branch: {
    loc: "Верхний Ад",
    bg: "night",
    text: "Первая глава подходит к концу. Слова и молчания уже что-то изменили.\n\nНочь. Выбор, который определит, как ты войдёшь дальше.",
    next: "final_choice",
  },
  final_choice: {
    loc: "Ночь",
    bg: "night",
    text: "Куда ты направляешь внимание?",
    choices: [
      { text: "Остаться рядом с обитателями Верхнего Ада.", next: "end_stay" },
      { text: "Разобраться в системе Небесной канцелярии.", next: "end_system" },
      { text: "Стать ближе к Элиасу — если он позволит.", next: "end_elias" },
      { text: "Узнать больше о семье Люцифера и Диона.", next: "end_family" },
      { text: "Посмотреть на Ад иначе, чем в первый день.", next: "end_vision" },
      { text: "Вернуться к порогу Каина.", next: "end_cain", reqFlag: "met_cain" },
    ],
  },

  end_stay: { text: "", ending: "stone_roots" },
  end_system: { text: "", ending: "protocol_cracks" },
  end_elias: { text: "", ending: "not_his_file" },
  end_family: { text: "", ending: "unnamed_family" },
  end_vision: { text: "", ending: "second_sight" },
  end_cain: { text: "", ending: "first_mark" },
};

export function interpolate(text: string, name: string) {
  return text.replaceAll("{name}", name || "Душа");
}

export function resolveEnding(key: string, flags: Record<string, boolean>) {
  if (key === "protocol_cracks" && flags.case_view) return "cold_archive";
  return key;
}
